import { Modal, TabsValue } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import SignInSignUp from "src/components/SignInSignUp";

const Home: NextPage = () => {
  const router = useRouter();
  const [opened, setOpened] = useState(false);
  const [activeTab, setActiveTab] = useState<TabsValue>("sign-in");

  useEffect(() => {
    if (router.query.signin !== undefined) {
      setActiveTab("sign-in");
      setOpened(true);
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Polyphemus</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        
      </main>

      <Modal
        closeOnClickOutside={true}
        opened={opened}
        onClose={() => setOpened(false)}
      >
        <SignInSignUp
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          setOpened={setOpened}
        />
      </Modal>
    </>
  );
};

export default Home;
