import { Container, Modal, TabsValue } from "@mantine/core";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import SignInSignUp from "src/components/SignInSignUp";
import type { MovieResult, TvResult } from "moviedb-promise";
import { tmdb } from "src/utils/tmdb";
import TrendingMovies from "src/components/Home/TrendingMovies";
import TrendingShows from "src/components/Home/TrendingShows";
import { MovieType, TVShowType } from "src/constants/types";

type HomeProps = {
  movies: MovieType[];
  shows: TVShowType[];
};

const Home = ({ movies, shows }: HomeProps) => {
  const router = useRouter();
  const [opened, setOpened] = useState(false);
  const [activeTab, setActiveTab] = useState<TabsValue>("sign-in");

  useEffect(() => {
    if (router.query.signin !== undefined) {
      setActiveTab("sign-in");
      setOpened(true);
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Polyphemus</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container my={36}>
        <TrendingMovies movies={movies} />
        <br />
        <TrendingShows shows={shows} />
      </Container>

      <Modal
        closeOnClickOutside={true}
        opened={opened}
        onClose={() => setOpened(false)}
      >
        <SignInSignUp
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          setOpened={setOpened}
        />
      </Modal>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const trendingMovies = await tmdb.trending({
    media_type: "movie",
    time_window: "day",
  });

  const movies = trendingMovies.results as unknown as MovieType[]

  const trendingShows = await tmdb.trending({
    media_type: "tv",
    time_window: "day",
  });
  const shows = trendingShows.results as unknown as TVShowType[];

  return {
    props: {
      movies,
      shows,
    },
    revalidate: 60 * 60 * 24, //24h
  };
};
